name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      METAFRM_UPLOADMODULE_URL: "https://download.metafrm.net/github/MetaFrameworkManagementSystemUploadModule.zip"
      METAFRM_UPLOADMODULE_ZIP: "MetaFrameworkManagementSystemUploadModule.zip"
      METAFRM_UPLOADMODULE_FILE: "MetaFrameworkManagementSystemUploadModule.dll"
      DLL_ID: 7
      DLL_PATH: "MetaFrm.Security.SHA512(net6.0)/bin/Release/net6.0/MetaFrm.Security.SHA512.dll"

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: 5.x


    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Debug
      run: dotnet build -c Debug --no-restore
      
    - name: Test Debug
      run: dotnet test -c Debug --no-build --verbosity normal

    - name: Build Release
      run: dotnet build -c Release --no-restore
      
    - name: Test Release
      run: dotnet test -c Release --no-build --verbosity normal


    - name: mkdir temp
      run: mkdir temp

    - name: cd temp
      run: cd temp

    - name: download
      run: wget -d "${{env.METAFRM_UPLOADMODULE_URL}}"

    - name: unzip
      run: unzip "${{env.METAFRM_UPLOADMODULE_ZIP}}"
      
    - name: Upload Module
      run: dotnet "${{env.METAFRM_UPLOADMODULE_FILE}}" ${{env.DLL_ID}} "${{env.DLL_PATH}}" "${{secrets.METAFRM_UPLOADMODULE_ACCESSKEY}}"

    - name: cd ..
      run: cd ..


    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
      
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json