name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Debug
      run: dotnet build -c Debug --no-restore
      
    - name: Test Debug
      run: dotnet test -c Debug --no-build --verbosity normal

    - name: Build Release
      run: dotnet build -c Release --no-restore
      
    - name: Test Release
      run: dotnet test -c Release --no-build --verbosity normal